const actionTypes = {
	FAV_ADD: 'FAV_ADD',
	FAV_REMOVE: 'FAV_REMOVE',
	FETCH_POST: 'FETCH_POST',
	FETCH_POST_SUCCESS: 'FETCH_POST_SUCCESS',
	FETCH_POST_ERROR: 'FETCH_POST_ERROR',
	NEW_POST: 'NEW_POST',
	NEW_POST_SUCCESS: 'NEW_POST_SUCCESS'
};
export default actionTypes;
